### PR TITLE
Mac compatibility

### PR DESCRIPTION
**Pull request by takorojo**
# Mac Compatibility

Mac users can now select .app files to run when OBS opens.  If told to close the programs when finished, the programs will shut down gracefully in order to minimize data loss on close.  This is the first step for multiplatform support requested in #1 and also mitigates #2 for Mac users, but not Windows users.

### CODE REVIEW

**Comment by jeabapLANG** [comment]
Hi thank you so much for your support !
Sadly I couldn't push forward the dev of this plugin due to my highschool and I was obligated to pause it.

For your commits think about reworking your check_os function because OBS embed LuaJit so no need to add special checkings and arch (x86, x64 etc) detection.

Cheers ;)

**Comment by takorojo** [comment]
Good to know!  That greatly simplifies things.  I'll go ahead and refactor accordingly.

Thank you for such a prompt reply!  😃

**Comment by jeabapLANG** [comment]
I will test if all of that works as soon as I go back home ;)
Thanks :)

**Comment by takorojo** [comment]
You're welcome!  I hope the Windows portion still works.  The Mac portion does, but I don't have a Windows machine to test it on at the moment.  Once I get a Linux VM up and running, I can work on getting Linux compatibility, too!

**Comment by jeabapLANG** [comment]
I already worked on the Linux compatibility and i'm testing both Windows & Linux thanks to a dual boot !
Only thing I couldn't test was Mac ah ah

**Pull request merged**
